item {
    name: "A16",
    id: 1,
    display_name: "A16"
}
item {
    name: "A23",
    id: 2,
    display_name: "A23"
}
item {
    name: "A27",
    id: 3,
    display_name: "A27"
}
item {
    name: "A28",
    id: 4,
    display_name: "A28"
}
item {
    name: "A3",
    id: 5,
    display_name: "A3"
}
item {
    name: "A32",
    id: 6,
    display_name: "A32"
}
item {
    name: "A39",
    id: 7,
    display_name: "A39"
}
item {
    name: "A4",
    id: 8,
    display_name: "A4"
}
item {
    name: "A40",
    id: 9,
    display_name: "A40"
}
item {
    name: "A43",
    id: 10,
    display_name: "A43"
}
item {
    name: "A56",
    id: 11,
    display_name: "A56"
}
item {
    name: "A59",
    id: 12,
    display_name: "A59"
}
item {
    name: "A8",
    id: 13,
    display_name: "A8"
}
item {
    name: "A80",
    id: 14,
    display_name: "A80"
}
item {
    name: "A90",
    id: 15,
    display_name: "A90"
}
item {
    name: "B10",
    id: 16,
    display_name: "B10"
}
item {
    name: "B11",
    id: 17,
    display_name: "B11"
}
item {
    name: "B29",
    id: 18,
    display_name: "B29"
}
item {
    name: "B3",
    id: 19,
    display_name: "B3"
}
item {
    name: "C110",
    id: 20,
    display_name: "C110"
}
item {
    name: "C124",
    id: 21,
    display_name: "C124"
}
item {
    name: "C15",
    id: 22,
    display_name: "C15"
}
item {
    name: "C16",
    id: 23,
    display_name: "C16"
}
item {
    name: "C6",
    id: 24,
    display_name: "C6"
}
item {
    name: "D281",
    id: 25,
    display_name: "D281"
}
item {
    name: "E1-0",
    id: 26,
    display_name: "E1-0"
}
item {
    name: "E10-1",
    id: 27,
    display_name: "E10-1"
}
item {
    name: "E100-0",
    id: 28,
    display_name: "E100-0"
}
item {
    name: "E115-0",
    id: 29,
    display_name: "E115-0"
}
item {
    name: "E119-1",
    id: 30,
    display_name: "E119-1"
}
item {
    name: "E120-1",
    id: 31,
    display_name: "E120-1"
}
item {
    name: "E120-2",
    id: 32,
    display_name: "E120-2"
}
item {
    name: "E121-0",
    id: 33,
    display_name: "E121-0"
}
item {
    name: "E122-0",
    id: 34,
    display_name: "E122-0"
}
item {
    name: "E13-1",
    id: 35,
    display_name: "E13-1"
}
item {
    name: "E130-0",
    id: 36,
    display_name: "E130-0"
}
item {
    name: "E132-0",
    id: 37,
    display_name: "E132-0"
}
item {
    name: "E14-1",
    id: 38,
    display_name: "E14-1"
}
item {
    name: "E145-0",
    id: 39,
    display_name: "E145-0"
}
item {
    name: "E148-0",
    id: 40,
    display_name: "E148-0"
}
item {
    name: "E151-0",
    id: 41,
    display_name: "E151-0"
}
item {
    name: "E155-0",
    id: 42,
    display_name: "E155-0"
}
item {
    name: "E17-0",
    id: 43,
    display_name: "E17-0"
}
item {
    name: "E200-1",
    id: 44,
    display_name: "E200-1"
}
item {
    name: "E201-0",
    id: 45,
    display_name: "E201-0"
}
item {
    name: "E204-1",
    id: 46,
    display_name: "E204-1"
}
item {
    name: "E29-1",
    id: 47,
    display_name: "E29-1"
}
item {
    name: "E3-0",
    id: 48,
    display_name: "E3-0"
}
item {
    name: "E30-1",
    id: 49,
    display_name: "E30-1"
}
item {
    name: "E35-1",
    id: 50,
    display_name: "E35-1"
}
item {
    name: "E39-0",
    id: 51,
    display_name: "E39-0"
}
item {
    name: "E44-1",
    id: 52,
    display_name: "E44-1"
}
item {
    name: "E52-0",
    id: 53,
    display_name: "E52-0"
}
item {
    name: "E63-1",
    id: 54,
    display_name: "E63-1"
}
item {
    name: "E69-1",
    id: 55,
    display_name: "E69-1"
}
item {
    name: "E8-0",
    id: 56,
    display_name: "E8-0"
}
item {
    name: "E80-1",
    id: 57,
    display_name: "E80-1"
}
item {
    name: "E82-1",
    id: 58,
    display_name: "E82-1"
}
item {
    name: "E83-0",
    id: 59,
    display_name: "E83-0"
}
item {
    name: "E98-0",
    id: 60,
    display_name: "E98-0"
}
item {
    name: "G229",
    id: 61,
    display_name: "G229"
}
item {
    name: "T380",
    id: 62,
    display_name: "T380"
}
item {
    name: "T383",
    id: 63,
    display_name: "T383"
}
item {
    name: "T386",
    id: 64,
    display_name: "T386"
}
