// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDMME1Ab3J2xOufLMMIT6LSHt0zsWx5AE',
    appId: '1:292622561727:android:5cde1067dca8937867710a',
    messagingSenderId: '292622561727',
    projectId: 'appfood-741d2',
    storageBucket: 'appfood-741d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdxgotUEIGd3SLy4ESg7Oxrve6AmyzdNs',
    appId: '1:292622561727:ios:6e93a4a4c0b8353d67710a',
    messagingSenderId: '292622561727',
    projectId: 'appfood-741d2',
    storageBucket: 'appfood-741d2.appspot.com',
    androidClientId: '292622561727-ikvknn7545m3hbt8iojsp4hfc50rm39o.apps.googleusercontent.com',
    iosClientId: '292622561727-e1ja6tfhn00dj0udqt0q0ooppqp1lk75.apps.googleusercontent.com',
    iosBundleId: 'com.example.appfood2',
  );
}
